# Repo desc
owner: BlissRoms-x86
repo: statuspage

sites:
  - name: Website
    url: https://blissos.org

status-website:
  cname: status.blissos.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BlissOS Status Page
  introTitle: "BlissOS Status Page"
  introMessage: This is the BlissOS Site uptime status page
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://blissos.org
