# Repo desc
owner: BlissRoms-x86
repo: statuspage

assignees:
  - TechExhibeo
  - ericswpark
  - Jackeagle

sites:
  - name: Website
    url: https://blissos.org
  - name: Blog
    url: https://blog.blissos.org
    assignees:
      - hmtheboy154
  - name: Documentation
    url: https://docs.blissos.org
    assignees:
      - hmtheboy154
  - name: Compatibility List
    url: https://tested.blissos.org
    assignees:
      - hmtheboy154

status-website:
  cname: status.blissos.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BlissOS Status Page
  introTitle: "BlissOS Status Page"
  introMessage: This is the BlissOS Site uptime status page
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://blissos.org

commitMessages:
  commitAuthorName: "BlissOS Bot"
  commitAuthorEmail: "bot@blissos.org"
